WildeRoverMgmtApp/WildeRoverMgmtApp/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using WildeRoverMgmtApp.Models;
using Microsoft.EntityFrameworkCore;

namespace WildeRoverMgmtApp.Controllers
{   
    [Authorize]
    public class OrderController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly WildeRoverMgmtAppContext _context;
        private OrderSummary _order;

        public OrderController(WildeRoverMgmtAppContext context, UserManager<User> userManager)
        {
            _userManager = userManager;
            _context = context;

            //Get latest OrderSummary  (TODO:  change to also query for user as well)
            var current = (from o in _context.OrderLog.Include("OrderList.Item")
                           orderby o.Date descending
                           select o).FirstOrDefault();

            //If there is no uncompleted order
            if (current == null || current.Completed)
            {
                //Create new OrderSummary
                current = new OrderSummary();
                current.Completed = false;
                current.Date = DateTime.Now;

                _context.OrderLog.Add(current);
                _context.SaveChanges();

                current = (from o in _context.OrderLog.Include("OrderList.Item")
                           orderby o.Date descending
                           select o).FirstOrDefault();
            }

            _order = current;
        }

        //Front House ORder Page
        //loadFromContext - If true, load count values from context, otherwise set values to 0
        [HttpGet]
        public async Task<IActionResult> FrontHouseOrder(bool? loadFromContext)
        {
            //Get FrontHouse Items
            var items = await (from i in _context.WildeRoverItem.Include(m => m.VendorItems)
                               where i.ItemHouse.HasFlag(WildeRoverItem.House.front)
                               orderby i.Type, i.SubType, i.Name
                               select i).ToListAsync();

            //Create View Model
            OrderViewModel ovm = new OrderViewModel();
            ovm.OrderId = _order.OrderSummaryId;

            //Populate View Model Order List
            foreach(var item in items)
            {
                //Create Item Count
                ItemCount temp = new ItemCount();
                temp.Item = item;
                temp.WildeRoverItemId = item.WildeRoverItemId;

                //If loadFromContext is false set count to 0
                if (loadFromContext == false)
                {
                    temp.Count = 0;
                }
                else  //load count from context
                {
                    temp.Count = temp.Item.Need;
                }                

                ovm.OrderList.Add(temp);  //add to view model
            }

            return View(ovm);            
        }

        //Post Method for FrontHouseOrder
        [HttpPost]
        public async Task<IActionResult> Save(OrderViewModel ovm)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    //Create dictionary of orderlist for O(1) access
                    var itemCountDict = _order.OrderList.ToDictionary(t => t.WildeRoverItemId);

                    foreach (var itemCount in ovm.OrderList)
                    {
                        //Find existing itemCount from _order

                        ItemCount temp;
                        if (itemCountDict.TryGetValue(itemCount.WildeRoverItemId, out temp))  //ItemCount found
                        {
                            if (itemCount.Count > 0)  //something is ordered
                            {
                                //Update ItemCount in context
                                temp.Count = itemCount.Count;
                                _context.ItemCounts.Update(temp);
                            }
                            else  //Item found but now its count is 0
                            {
                                //Remove ItemCount from context
                                _order.OrderList.Remove(temp);
                                _context.ItemCounts.Remove(temp);
                            }
                        }
                        else  //ItemCount does not exist in context
                        {
                            if (itemCount.Count > 0)
                            {
                                //Create ItemCount
                                temp = new ItemCount();
                                temp.OrderSummary = _order;
                                temp.OrderSummaryId = _order.OrderSummaryId;
                                temp.WildeRoverItemId = itemCount.WildeRoverItemId;
                                temp.Count = itemCount.Count;

                                //Add to context
                                _context.ItemCounts.Add(temp);

                                //Add to OrderSummary
                                _order.OrderList.Add(temp);                            
                            }
                        }
                    }

                    //Update Last Edited
                    var user = await _userManager.GetUserAsync(User);
                    if (user == null) throw new InvalidOperationException();

                    _order.LastEdited = user.FullName;

                    //Update context
                    _context.OrderLog.Update(_order);
                    await _context.SaveChangesAsync();  //save context
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }

                return RedirectToAction("Index", "OrderSummary");
            }

            return View(ovm);
        }        

        //Reset Post action
        //[HttpPost]
        public IActionResult FrontHouseOrderReset()
        {
            //Redirect to FrontHouse setting loadFromContext to false
            return RedirectToAction("FrontHouseOrder", new { loadFromContext = false });
        }

        //Submit Post action
        [HttpPost]
        public async Task<IActionResult> Submit(OrderViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    //Save order before submitting

                    //Create dictionary of orderlist for O(1) access
                    var itemCountDict = _order.OrderList.ToDictionary(t => t.WildeRoverItemId);

                    foreach (var itemCount in model.OrderList)
                    {
                        //Find existing itemCount from _order
                        ItemCount temp;
                        if (itemCountDict.TryGetValue(itemCount.WildeRoverItemId, out temp))  //ItemCount found
                        {
                            if (itemCount.Count > 0)  //something is ordered
                            {
                                //Update ItemCount in context
                                temp.Count = itemCount.Count;
                                _context.ItemCounts.Update(temp);
                            }
                            else  //Item found but now its count is 0
                            {
                                //Remove ItemCount from context
                                _order.OrderList.Remove(temp);
                                _context.ItemCounts.Remove(temp);
                            }
                        }
                        else  //ItemCount does not exist in context
                        {
                            if (itemCount.Count > 0)
                            {
                                //Create ItemCount
                                temp = new ItemCount();
                                temp.OrderSummary = _order;
                                temp.OrderSummaryId = _order.OrderSummaryId;
                                temp.WildeRoverItemId = itemCount.WildeRoverItemId;
                                temp.Count = itemCount.Count;

                                //Add to context
                                _context.ItemCounts.Add(temp);

                                //Add to OrderSummary
                                _order.OrderList.Add(temp);
                            }
                        }
                    }

                    //Update Last Edited
                    var user = await _userManager.GetUserAsync(User);
                    if (user == null) throw new InvalidOperationException();

                    _order.LastEdited = user.FullName;

                    //Update context
                    _context.OrderLog.Update(_order);
                    await _context.SaveChangesAsync();  //save context
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }

                //Redirect to Submit Page in OrderSummary
                return RedirectToAction("Submit", "OrderSummary", new { id = model.OrderId });
            }

            return View(model);
        }

        //Back House Order Page
        //loadFromContext - If true, load count values from context, otherwise set values to 0
        [HttpGet]
        public async Task<IActionResult> BackHouseOrder(bool? loadFromContext)
        {
            //Get FrontHouse Items
            var items = await (from i in _context.WildeRoverItem.Include(m => m.VendorItems)
                               where i.ItemHouse.HasFlag(WildeRoverItem.House.back)
                               orderby i.Type, i.SubType, i.Name
                               select i).ToListAsync();

            //Create View Model

WildeRoverMgmtApp/WildeRoverMgmtApp/Controllers/VendorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WildeRoverMgmtApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace WildeRoverMgmtApp.Controllers
{
    [Authorize]
    public class VendorsController : Controller
    {
        private readonly WildeRoverMgmtAppContext _context;

        public VendorsController(WildeRoverMgmtAppContext context)
        {
            _context = context;    
        }

        // GET: Vendors
        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Vendor.ToListAsync());
        }

        // GET: Vendors/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vendor = await _context.Vendor
                .SingleOrDefaultAsync(m => m.VendorId == id);
            if (vendor == null)
            {
                return NotFound();
            }

            return View(vendor);
        }

        [Authorize]
        // GET: Vendors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Vendors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("VendorId,Name,Phone,Email,PointOfContact")] Vendor vendor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(vendor);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(vendor);
        }

        // GET: Vendors/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vendor = await _context.Vendor.SingleOrDefaultAsync(m => m.VendorId == id);
            if (vendor == null)
            {
                return NotFound();
            }
            return View(vendor);
        }

        // POST: Vendors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("VendorId,Name,Phone,EMail,PointOfContact")] Vendor vendor)
        {
            if (id != vendor.VendorId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vendor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VendorExists(vendor.VendorId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(vendor);
        }

        public Task<IActionResult> Delete(int id)
        {
            return DeleteConfirmed(id);
        }

        // POST: Vendors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var vendor = await _context.Vendor.SingleOrDefaultAsync(m => m.VendorId == id);
            if (vendor == null) return NotFound();

            _context.Vendor.Remove(vendor);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool VendorExists(int id)
        {
            return _context.Vendor.Any(e => e.VendorId == id);
        }
    }
}

WildeRoverMgmtApp/WildeRoverMgmtApp/Views/Shared/_Layout.cshtml
@using WildeRoverMgmtApp.Models
@using System.Security.Claims
@using Microsoft.AspNetCore.Identity
@inject UserManager<User> userManager
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet

@{ 
    var userInfo = await userManager.GetUserAsync(User);
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WildeRoverMgmtApp</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootswatch/yeti/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    @*<environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment names="Staging,Production">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>
        @Html.Raw(JavaScriptSnippet.FullScript)*@
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">WildeRoverMgmtApp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle">Inventory<span class="caret"/></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Inventory" asp-action="FrontHouseIndex">FOH</a></li>
                            <li><a asp-area="" asp-controller="Inventory" asp-action="BackHouseInventory">BOH</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle">Order<span class="caret"/></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Order" asp-action="FrontHouseOrder">FOH</a></li>
                            <li><a asp-area="" asp-controller="Order" asp-action="BackHouseOrder">BOH</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle">Admin<span class="caret"/></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="WildeRoverItems" asp-action="Index">Wilde Rover Items</a></li>
                            <li><a asp-area="" asp-controller="VendorItems" asp-action="Index">Vendor Items</a></li>
                            <li><a asp-area="" asp-controller="Vendors" asp-action="Index">Vendors</a></li>
                            <li><a asp-area="" asp-controller="InventorySummary" asp-action="Index">Inventory Log</a></li>
                            <li><a asp-area="" asp-controller="OrderSummary" asp-action="Index">Order Log</a></li>
                            <li><a asp-area="" asp-controller="InventoryArea" asp-action="Index">Inventory Areas</a></li>
                        </ul>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="dropdown">
                            <a data-toggle="dropdown" class="dropdown-toggle">
                                @Html.DisplayFor(m => userInfo.FullName)
                                <span class="caret" />
                            </a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="Account" asp-action="Details">Account Details</a></li>
                                <li><a asp-area="" asp-controller="Account" asp-action="Edit">Edit</a></li>
                                <li><a asp-area="" asp-controller="Account" asp-action="ChangePassword">Change Password</a></li>
                                <li><a asp-area="" asp-controller="Account" asp-action="Logout">Sign Out</a></li>
                            </ul>
                        </li>
                    }
                    else
                    {
                        <li>
                            <a asp-controller="Account" asp-action="Login">Sign In</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - WildeRoverMgmtApp</p>
        </footer>
    </div>

    @*<environment names="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment names="Staging,Production">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>*@

    @RenderSection("Scripts", required: false)
</body>
</html>