WildeRoverMgmtApp/WildeRoverMgmtApp/Models/WildeRoverItem.cs
using System;
using System.Collections.Generic;
using System.Text;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace WildeRoverMgmtApp.Models
{
    public partial class WildeRoverItem : IInventoriable, IOrderable, IComparable<WildeRoverItem>
    {
        public enum House
        {
            [Display(Name = "Front of House")]
            front = 1,
            [Display(Name = "Back of House")]
            back = 2,
            [Display(Name = "Front and Back")]
            both = 3
        };

        public WildeRoverItem()
        {
            VendorItems = new HashSet<VendorItem>();
        }

        #region Entity

        [Key]
        public int WildeRoverItemId { get; set; }

        [Display(Name = "House Item")]
        public string Name { get; set; }

        public int Par { get; set; }

        [Range(0,int.MaxValue)]
        public int Have { get; set; }

        [Required]
        public string Type { get; set; }

        [Required]
        public string SubType { get; set; }

        [Required]
        public House ItemHouse { get; set; }

        public HashSet<VendorItem> VendorItems { get; set; }      
        
        [NotMapped]
        public int Need { get { return Par - Have; } }

        //public int? DefaultVendorItemId { get; set; }
        //private VendorItem _defaultVendorItem;
        [NotMapped]
        public VendorItem DefaultVendorItem
        {
            get
            {
                decimal minPPU = Decimal.MaxValue;
                VendorItem returnVal = null;
                foreach (var item in VendorItems)
                {
                    decimal pricePerUnit = item.Price / item.PackSize;
                    if (pricePerUnit < minPPU)
                    {
                        minPPU = pricePerUnit;
                        returnVal = item;
                    }
                }

                return returnVal;
            }         
        }

        //public VendorItem GetDefaultVendorItem ()
        //{
        //    if (DefaultVendorItemId == null)
        //    {
        //        decimal minPPU = Decimal.MaxValue;
        //        VendorItem returnVal = null;
        //        foreach (var item in VendorItems)
        //        {
        //            decimal pricePerUnit = item.Price / item.PackSize;
        //            if (pricePerUnit < minPPU)
        //            {
        //                minPPU = pricePerUnit;
        //                returnVal = item;
        //            }
        //        }

        //        return returnVal;
        //    }
        //    else
        //    {
        //        return DefaultVendorItem;
        //    }
        //}

        ////[NotMapped]
        //[Display(Name = "Default Vendor Item")]
        //public VendorItem DefaultVendorItem
        //{
        //    get
        //    {
        //        if (DefaultVendorItemId == null)
        //        {
        //            decimal minPPU = Decimal.MaxValue;
        //            VendorItem returnVal = null;
        //            foreach (var item in VendorItems)
        //            {
        //                decimal pricePerUnit = item.Price / item.PackSize;
        //                if (pricePerUnit < minPPU)
        //                {
        //                    minPPU = pricePerUnit;
        //                    returnVal = item;
        //                }
        //            }

        //            return returnVal;
        //        }
        //        else
        //        {
        //            return _defaultVendorItem;
        //        }

        //    }
        //    set { _defaultVendorItem = value; }
        //}

        #endregion Entity

        #region IInventoriable

        //TODO: Implement
        public string ToStringInventory()
        {
            throw new NotImplementedException();
        }

        #endregion IInventoriable

        #region IOrderable

        public int OrderCount { get; set; }

        #endregion IOrderable

        
        //TODO: Implement
        public string ToStringOrder()
        {
            throw new NotImplementedException();
        }

        #region IComparable

        public int CompareTo(WildeRoverItem other)
        {
            if (this.Type == other.Type)
            {
                return this.Name.CompareTo(other.Name);
            }
            else
            {
                return this.Type.CompareTo(other.Type);
            }
        }

        #endregion IComparable



    }
}

WildeRoverMgmtApp/WildeRoverMgmtApp/Controllers/WildeRoverItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WildeRoverMgmtApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace WildeRoverMgmtApp.Controllers
{
    [Authorize]
    public class WildeRoverItemsController : Controller
    {
        private readonly WildeRoverMgmtAppContext _context;

        public WildeRoverItemsController(WildeRoverMgmtAppContext context)
        {
            _context = context;
        }

        // GET: WildeRoverItems
        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _context.WildeRoverItem.ToListAsync());
        }


        // GET: WildeRoverItems/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var wildeRoverItem = await _context.WildeRoverItem.Include("VendorItems.Vendor")
                .SingleOrDefaultAsync(m => m.WildeRoverItemId == id);
            if (wildeRoverItem == null)
            {
                return NotFound();
            }


            return View(wildeRoverItem);
        }

        // GET: WildeRoverItems/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: WildeRoverItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("WildeRoverItemId,Name,Par,Have,Type, SubType")] WildeRoverItem wildeRoverItem)
        {
            if (ModelState.IsValid)
            {
                _context.Add(wildeRoverItem);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }        

            return View(wildeRoverItem);            
        }

        // GET: WildeRoverItems/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var wildeRoverItem = await _context.WildeRoverItem.SingleOrDefaultAsync(m => m.WildeRoverItemId == id);
            if (wildeRoverItem == null)
            {
                return NotFound();
            }

            return View(wildeRoverItem);
        }

        // POST: WildeRoverItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("WildeRoverItemId,Name,Par,Have,Type,SubType")] WildeRoverItem wildeRoverItem)
        {
            if (id != wildeRoverItem.WildeRoverItemId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(wildeRoverItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WildeRoverItemExists(wildeRoverItem.WildeRoverItemId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(wildeRoverItem);
        }

        [HttpGet]
        public Task<IActionResult> Delete(int id)
        {
            return DeleteConfirmed(id);
        }

        // POST: WildeRoverItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var wildeRoverItem = await _context.WildeRoverItem.SingleOrDefaultAsync(m => m.WildeRoverItemId == id);
            _context.WildeRoverItem.Remove(wildeRoverItem);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool WildeRoverItemExists(int id)
        {
            return _context.WildeRoverItem.Any(e => e.WildeRoverItemId == id);
        }
    }
}

WildeRoverMgmtApp/WildeRoverMgmtApp/Views/WildeRoverItems/Create.cshtml
@model WildeRoverMgmtApp.Models.WildeRoverItem

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>WildeRoverItem</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Par" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Par" class="form-control" />
                <span asp-validation-for="Par" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Have" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Have" class="form-control" />
                <span asp-validation-for="Have" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Type" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="SubType" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="SubType" class="form-control" />
                <span asp-validation-for="SubType" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 btn-group">
                <input type="submit" value="Save" class="btn btn-success" />
                <a class="btn btn-danger" asp-action="Index">Cancel</a> 
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WildeRoverMgmtApp/WildeRoverMgmtApp/Views/WildeRoverItems/Delete.cshtml
@model WildeRoverMgmtApp.Models.WildeRoverItem

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>WildeRoverItem</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="WildeRoverItemId" />
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Par)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Par)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Have)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Have)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SubType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SubType)
        </dd></dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color btn-group">
            <input type="submit" value="Delete" class="btn btn-danger" />
            <a class="btn btn-primary" asp-action="Index">Cancel</a> 
        </div>
    </form>
</div>

WildeRoverMgmtApp/WildeRoverMgmtApp/Views/WildeRoverItems/Details.cshtml
@model WildeRoverMgmtApp.Models.WildeRoverItem

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>WildeRover Item</h4>
    <hr />
    <dl class="dl">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Par)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Par)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Have)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Have)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SubType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SubType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DefaultVendorItem)
        </dt>        
            @if (Model.DefaultVendorItem == null)
            {
                <dd>NULL</dd>
            }
            else
            {
                <dd>@Html.DisplayFor(model => model.DefaultVendorItem.Vendor.Name)</dd>
            }  
    </dl>
</div>
<div class="container">
    <h4>
        <a href="#VendorItems" data-toggle="collapse">
            Vendor Items<span class="caret" />
        </a>
    </h4>
        <div id="VendorItems" class="collapse">
            <table class="table table-hover table-condensed">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.VendorItems.FirstOrDefault().Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.VendorItems.FirstOrDefault().Vendor.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.VendorItems.FirstOrDefault().PackSize)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.VendorItems.FirstOrDefault().Price)
                        </th>
                        <th>
                            PPU
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.VendorItems == null)
                    {
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.VendorItems.FirstOrDefault().PPU)
                            </td>
                        </tr>
                    }
                    else                    {

                        @foreach (var vi in Model.VendorItems)
                        {
                            string trClass;
                            if (vi.VendorItemId == Model.DefaultVendorItem.VendorItemId)
                            {
                                trClass = "bg-info";
                            }
                            else
                            {
                                trClass = string.Empty;
                            }
                            <tr class="@trClass">
                                <td>
                                    @Html.DisplayFor(i => vi.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(i => vi.Vendor.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(i => vi.PackSize)
                                </td>
                                <td>
                                    @Html.DisplayFor(i => vi.Price)
                                </td>
                                <td>
                                    @Html.DisplayFor(i => vi.PPU)
                                </td>
                            </tr>
                        }
                    }
                </tbody>
      </table>
    </div>
</div>
<hr />
<div class="btn-group">
    <a class="btn btn-success" style="text-decoration:none" asp-action="Edit" asp-route-id="@Model.WildeRoverItemId">Edit</a>    
    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#popupModal">Delete</button>
    <a class="btn btn-info" style="text-decoration:none" href="javascript:history.go(-1)">Back</a>
</div>

<div class="modal fade" id="popupModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3 class="modal-title">
                    Delete
                </h3>
                <h4>
                    @Html.DisplayFor(m => m.Name)
                </h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to Delete?</p>
            </div>
            <div class="modal-footer">
                <div class="btn-group">
                    <a class="btn btn-success" asp-controller="WildeRoverItems" asp-action="Delete" asp-route-id="@Model.WildeRoverItemId">
                        Yes
                    </a>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
                </div>
            </div>
        </div>
    </div>
</div>

WildeRoverMgmtApp/WildeRoverMgmtApp/Views/WildeRoverItems/Edit.cshtml
@model WildeRoverMgmtApp.Models.WildeRoverItem

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>WildeRoverItem</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="WildeRoverItemId" />
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Par" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Par" class="form-control" />
                <span asp-validation-for="Par" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Have" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Have" class="form-control" />
                <span asp-validation-for="Have" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Type" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="SubType" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="SubType" class="form-control" />
                <span asp-validation-for="SubType" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 btn-group">
                <input type="submit" value="Save" class="btn btn-success" />
                <a class="btn btn-danger" asp-action="Index">Cancel</a> 
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WildeRoverMgmtApp/WildeRoverMgmtApp/Views/WildeRoverItems/Index.cshtml
@model IEnumerable<WildeRoverMgmtApp.Models.WildeRoverItem>

@{
    ViewData["Title"] = "Index";
}

<h2>WildeRover Items</h2>

<p>
    <a asp-action="Create" class="btn btn-success">Create New</a>
</p>

<body>
    <div>
        <table class="table table-hover table-condensed">
            <!--Table head-->
            <thead class="thead-inverse">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Par)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Have)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Type)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.SubType)
                    </th>
                </tr>
            </thead>
            <!--Table head-->
            <tbody>
                @foreach (var item in Model)
            {
                    <tr>
                        <td>
                            <a class="btn" style="text-decoration:none" asp-action="Details" asp-route-id="@item.WildeRoverItemId">
                                @Html.DisplayFor(modelItem => item.Name)
                            </a>
                        </td>
                        <td>
                            <a class="btn">
                                @Html.DisplayFor(modelItem => item.Par)
                            </a>
                        </td>
                        <td>
                            <a class="btn">
                                @Html.DisplayFor(modelItem => item.Have)
                            </a>
                        </td>
                        <td>
                            <a class="btn">
                                @Html.DisplayFor(modelItem => item.Type)
                            </a>
                        </td>
                        <td>
                            <a class="btn">
                                @Html.DisplayFor(modelItem => item.SubType)
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>