WildeRoverMgmtApp/WildeRoverMgmtApp/Models/OrderSummary.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;

namespace WildeRoverMgmtApp.Models
{
    public class OrderSummary
    {
        public OrderSummary()
        {
            OrderList = new List<ItemCount>();
        }

        [Key]
        public int OrderSummaryId { get; set; }
        public DateTime Date { get; set; }
        public bool Completed { get; set; }

        [DisplayFormat(DataFormatString = "{0:C}")]
        public decimal Total { get; set; }

        [Display(Name = "Last Edited By")]
        public string LastEdited { get; set; }

        public virtual List<ItemCount> OrderList { get; set; }

        public decimal CalculateTotal()
        {
            decimal total = 0m;

            foreach(var ic in OrderList)
            {
                total += ic.Item.DefaultVendorItem.Price * ic.Count;
            }

            return total;
        }
    }
}

WildeRoverMgmtApp/WildeRoverMgmtApp/Controllers/OrderSummaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using WildeRoverMgmtApp.Models;

namespace WildeRoverMgmtApp.Controllers
{
    [Authorize]
    public class OrderSummaryController : Controller
    {
        private readonly WildeRoverMgmtAppContext _context;

        public OrderSummaryController(WildeRoverMgmtAppContext context)
        {
            _context = context;
        }

        //Action to view a list of all orders
        public async Task<IActionResult> Index()
        {
            var order = from o in _context.OrderLog
                        orderby o.Date descending
                        select o;

            return View(await order.ToListAsync());
        }

        //Page to see the details of an OrderSummary
        //id - Id of OrderSummary
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();  //Validate

            //Get OrderSummary
            var order = await (from o in _context.OrderLog.Include("OrderList.Item")
                               where o.OrderSummaryId == id
                               select o).SingleOrDefaultAsync();

            if (order == null) return NotFound();  //validate

            return View(order);
        }

        //Submit page for selected OrderSummary
        //id - Id of OrderSummary
        [HttpGet]
        public async Task<IActionResult> Submit(int? id)
        {
            if (id == null) return NotFound();  //Validate

            //Get OrderSummary from context
            var order = await (from log in _context.OrderLog.Include("OrderList.Item.VendorItems.Vendor")
                               where log.OrderSummaryId == id
                               select log).SingleOrDefaultAsync();

            if (order == null) return NotFound(); //Validate

            //Create view model
            OrderSubmitViewModel osvm = new OrderSubmitViewModel();
            osvm.Order = order;
            osvm.OrderSummaryId = order.OrderSummaryId;
            osvm.Total = order.CalculateTotal();

            //Populate view model OrderItems
            foreach(var itemCount in order.OrderList)
            {
                List<ItemCount> tempList;
                //int key = itemCount.Item.DefaultVendorItem.Vendor.VendorId;
                var key = itemCount.Item.DefaultVendorItem.Vendor;
                if (!osvm.OrderItems.TryGetValue(key, out tempList))  //Key found in view model OrderItems
                {
                    //Add new dictionary entry
                    tempList = new List<ItemCount>();
                    osvm.OrderItems.Add(key, tempList);
                }

                //Add itemCount to OrderItems
                tempList.Add(itemCount);
            }

            return View(osvm);
        }

        //Submit Post Method
        [HttpPost]
        public async Task<IActionResult> Submit(int? id, OrderSubmitViewModel osvm)
        {
            if (id == null) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    //get OrderSummary
                    var order = await (from log in _context.OrderLog.Include("OrderList.Item.VendorItems.Vendor")
                                       where log.OrderSummaryId == id
                                       select log).SingleOrDefaultAsync();

                    if (order == null) return NotFound();  //Validate


                    //====EMAIL VENDORS HERE===================================




                    //=========================================================

                    //Update OrderSummary
                    order.Completed = true;
                    order.Total = osvm.Total;

                    _context.OrderLog.Update(order);  //update context

                    await _context.SaveChangesAsync();  //save context

                    return RedirectToAction("Index");

                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
    }
}

WildeRoverMgmtApp/WildeRoverMgmtApp/Views/OrderSummary/Details.cshtml
@model WildeRoverMgmtApp.Models.OrderSummary

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(m => m.Date)
        </dt>
        <dd>
            @Html.DisplayFor(m => m.Date)
        </dd>
        <dt>
            @Html.DisplayNameFor(m => m.Completed)
        </dt>
        @if(Model.Completed)
        {
            <dd><b>Yes</b></dd>
        }
        else
        {
            <dd><b>No</b></dd>
        }
        <dt>
            @Html.DisplayNameFor(m => m.LastEdited)
        </dt>
        <dd>
            @Html.DisplayFor(m => m.LastEdited)
        </dd>
    </dl>
</div>

<hr />
<table class="table table-hover table-condensed">
    <thead>
        <tr>
            <th>
                <div class="col-md-10">
                    @Html.DisplayNameFor(model => model.OrderList.FirstOrDefault().Item.Name)
                </div>
            </th>
            <th>
                <div class="col-md-2">
                    @Html.DisplayNameFor(model => model.OrderList.FirstOrDefault().Count)
                </div>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var itemCount in Model.OrderList)
        {
            <tr>
                <td>
                    <div class="col-md-10">
                        <a class="btn" asp-controller="WildeRoverItems" asp-action="Details" asp-route-id="@itemCount.Item.WildeRoverItemId">
                            @Html.DisplayFor(m => itemCount.Item.Name)
                        </a>
                    </div>
                </td>
                <td>
                    <div class="col-md-2">
                        @Html.DisplayFor(m => itemCount.Count)
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
<div>
    <dl class="dl">
        <dt>Price</dt>
        @if (Model.Completed)
        {
            <dd>
                <h3>@Html.DisplayFor(m => Model.Total)</h3>
            </dd>
        }
        else
        {
            <dd><h3>TBD</h3></dd>
        }
    </dl>
</div>

@if (!Model.Completed)
{
    <div class="btn-group">
        @if (Model.OrderList.Count != 0)
        {
            <a class="btn btn-success" asp-controller="OrderSummary" asp-action="Submit" asp-route-id="@Model.OrderSummaryId">
                Submit
            </a>
        }
        <a class="btn btn-info" style="text-decoration:none" href="javascript:history.go(-1)">Back</a>
    </div>
}

WildeRoverMgmtApp/WildeRoverMgmtApp/Views/OrderSummary/Index.cshtml
@model IEnumerable<WildeRoverMgmtApp.Models.OrderSummary>

    @{
        ViewData["Title"] = "Order Log";
    }

    <h2>Order Log</h2>

    <body>
        <table class="table table-hover table-condensed">
            <thead class="thead-inverse">
                <tr>
                    <th>
                        <div class="col-md-5">
                            @Html.DisplayNameFor(model => model.Date)
                        </div>
                    </th>
                    <th>
                        <div class="col-md-5">
                            @Html.DisplayNameFor(model => model.LastEdited)
                        </div>
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Completed)
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var log in Model)
                {
                    <tr>
                        <td>
                            <div class="col-md-5">
                                <a class="btn" asp-controller="OrderSummary" asp-action="Details" asp-route-id="@log.OrderSummaryId">
                                    @Html.DisplayFor(modelItem => log.Date)
                                </a>
                            </div>
                        </td>
                        <td>
                            <div class="col-md-5">
                                <a class="btn">
                                    @Html.DisplayFor(model => log.LastEdited)
                                </a>
                            </div>
                        </td>
                        <td>
                            <div class="col-md-2">
                                   @if (log.Completed)
                                   {
                                    <a class="btn">Yes</a>                                       
                                   }
                                   else
                                   {
                                       <a class="btn">No</a>
                                   }
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </body>

WildeRoverMgmtApp/WildeRoverMgmtApp/Views/OrderSummary/Submit.cshtml
@model WildeRoverMgmtApp.Models.OrderSubmitViewModel

@{
    ViewData["Title"] = "Submit";
}


<style type="text/css">
    td {
        padding: 0 10px 0 10px;
    }

    th {
        padding: 0 10px 0 10px;
    }
</style>

<h2>Order Submit</h2>

<h3>
    @Html.DisplayFor(model => model.Order.Date)
</h3>

<hr />

@using (Html.BeginForm("Submit", "OrderSummary", FormMethod.Post))
{
    <div>
        @Html.HiddenFor(model => model.OrderSummaryId)
        @Html.HiddenFor(model => model.Total)
        @foreach (var kvp in Model.OrderItems)
        {
            <div class="container">
                <h3>
                    <a href="#@kvp.Key.VendorId" data-toggle="collapse">
                        @Html.DisplayFor(model => kvp.Key.Name)
                        <span class="caret"></span>
                    </a>                    
                </h3>
                <div id="@kvp.Key.VendorId" class="collapse">
                    <table class="table table-hover table-condensed">
                        <thead>
                            <tr>
                                <th>
                                    <div class="col-md-10"></div>
                                </th>
                                <th>
                                    <div class="col-md-2">
                                        Count
                                    </div>
                                </th>
                            </tr>
                        </thead>
                        <tbody id="childtable">
                            @Html.EditorFor(model => kvp.Value)
                        </tbody>
                    </table>
                </div>
            </div>
        }
    </div>
    <p>
        <dl class="dl">
            <dt>Total: </dt>
            <dd>
                <h3>@Html.DisplayFor(model => model.Total)</h3>
            </dd>
        </dl>
    </p>
    <div class="btn-group">
        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#popupModal">Submit</button>
        <a class="btn btn-info" href="javascript:history.go(-1)">Back</a>
    </div>

    <!--  Modal Popup Dialog-->
    <div class="modal fade" id="popupModal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h3>Submit</h3>
                    <h4 class="modal-title">
                        @Html.DisplayFor(m => m.Order.Date)
                    </h4>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to Submit?</p>
                </div>
                <div class="modal-footer">
                    <div btn-group>
                        <input type="submit" class="btn btn-success" value="Yes" />
                        <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}